Update automation_workflow.yml to check for changes in package.json and CHANGELOG.md files

diff --git a/.github/workflows/automation_workflow.yml b/.github/workflows/automation_workflow.yml
--- a/.github/workflows/automation_workflow.yml
+++ b/.github/workflows/automation_workflow.yml
@@ -12,16 +12,22 @@ jobs:
   check-files:
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
+      - uses: actions/checkout@v2
 
-      - name: Check for Changed Files
-        uses: brettcannon/check-for-changed-files@v1.2.0
+      - name: Changed Files
+        uses: tj-actions/changed-files@v42.0.4
+        id: changed-files
         with:
-          file-pattern: |
+          files: |
             package.json
             CHANGELOG.md
-            RELEASE
+            LICENSE
+
+      - name: Verify Changes
+        if: ${{ steps.changed-files.outputs.any_changed == 'false' }}
+        run: |
+          echo "Error: package.json or CHANGELOG.md must be updated."
+          exit 1
 
   auto-create-pr-to-dev-main:
     runs-on: ubuntu-latest
